### PR TITLE
Add support for last seed effects

### PR DESCRIPTION
**Pull request by markooda**
This is just a slight modification I've done to support the player needs from the Last Seed mod for my personal use but you can add it into the main mod if you want.

ScreenShot1

### CODE REVIEW

**Comment by mlthelama** [comment]
Thanks, will take a look at it later today 👍

**Comment by sinthoras50** [comment]
> Thanks, will take a look at it later today 👍


 Nice, wasn't sure if you were accepting PRs. I should probably add that I changed some files that didn't need changing (pch, perkvisitor). This is my first time working with a skse plugin or a c++ project in general so I was figuring stuff out. Should've cleaned that up.

An example use would be to add an entry into the player json file:

// supported keys are: hunger, thirst, fatigue, vitality
{
      "key": "hunger",
      "display_name": "$ShowHunger",
      "icon_string": "default_food",
      "stats_column": "player",
      "stats_inventory_column": "none"
}

And then there's also the translation, mod detection jsons + I also added 2 new icons. I can upload the modified swf and fla if you do intend to use them.

**Comment by mlthelama** [comment]
always happy to take pull requests to implement other mods. for the modified swf/flash you could make a PR to my forked skyui repo. (is added here as submodule) [seen here](https://github.com/mlthelama/SkyrimCharacterSheet/tree/main/extern)
yes we can add the values to the json or make a "SkyrimCharacterSheet_Player_LastSeed.json" because that should be read to by my code. and then add the translation to [here](https://github.com/mlthelama/SkyrimCharacterSheet/blob/main/swf/Translations/SkyrimCharacterSheet_english.txt)

**Comment by sinthoras50** [comment]
Ah yeah sorry, didnt see that the config/translation files were actually included in this project, I updated them now and also made a PR toward your forked skyui repo with the new icons

**Comment by mlthelama** [comment]
all good. merged the pr in the fork

**Pull request merged**
